[{link: "https://blog.yossarian.net/2020/01/23/Anybody-can-write-good-bash-with-a-little-effort", priority: :medium, tags:["command-line"] },
{link: "https://github.com/ramitsurana/awesome-kubernetes", priority: :high, tags:["comprehensive", "k8s"] },
{link: "https://1loc.dev/}", priority: :medium, tags: ["js", "comprehensive"]},
{link: "https://qz.com/work/1836105/20-great-questions-to-ask-instead-of-how-are-you-doing-right-now/", priority: :medium, tags:["management"] },
{link: "https://github.com/ankane/lockbox", priority: :low, tags:["rails", "ruby"] },
{link: "https://www.blameless.com/thought-leadership-panel-real-sre/", priority: :low, tags:["management", "reliabiltiy"] },
{link: "https://blog.twitter.com/engineering/en_us/topics/open-source/2020/hunting-a-linux-kernel-bug.html", priority: :low, tags:["misc"] },
{link: "https://segment.com/blog/introducing-centrifuge/", priority: :high, tags:["data-structures", "misc"] },
{link: "https://github.com/dandavison/delta", priority: :high, tags:["command-line", "git", "tooling"] },
{link: "https://github.com/matt-harvey/git_curate", priority: :low, tags:["command-line", "git"] },
{link: "https://blog.arkency.com/practical-use-of-ruby-pstore/", priority: :medium, tags:["ruby"] },
{link: "https://github.blog/2020-03-26-february-service-disruptions-post-incident-analysis/", priority: :low, tags:["reliability"] },
{link: "https://danluu.com/corp-eng-blogs/", priority: :medium, tags:["misc"] },
{link: "https://robertheaton.com/2020/04/27/how-does-a-tcp-reset-attack-work/", priority: :medium, tags:["security", "networking"] },
{link: "https://resilienceroundup.com/issues/73/", priority: :high, tags:["reliability"] },
{link: "https://timkadlec.com/remembers/2020-04-21-the-cost-of-javascript-frameworks/", priority: :medium, tags:["front-end", "js"] },
{link: "https://github.com/ksindi/managers-playbook", priority: :medium, tags:["management"] },
{link: "https://www.firehydrant.io/blog/failover-conf-wrapup/", priority: :low, tags:["reliability"] },
{link: "https://www.blameless.com/failover-conf/", priority: :high, tags:["reliability"] },
{link: "https://www.atlassian.com/blog/it-teams/how-to-create-an-incident-response-playbook", priority: :medium, tags:["reliability"] },
{link: "https://speakerdeck.com/jallspaw/incident-analysis-how-star-learning-star-is-different-than-star-fixing-star?slide=26", priority: :low, tags:["reliability"] },
{link: "https://zwischenzugs.com/2018/06/08/anatomy-of-a-linux-dns-lookup-part-i/", priority: :high, tags:["networking"] },
{link: "https://blog.reversinglabs.com/blog/mining-for-malicious-ruby-gems", priority: :high, tags:["ruby", "security"] },
{link: "http://rachelbythebay.com/w/2020/04/23/rel/", priority: :high, tags:["misc", "reliability"] },
{link: "https://advancedbeginners.substack.com/p/pfab-13-when-code-is-too-clever-to", priority: :high, tags:["programming-tips"] },
{link: "https://nebulab.it/blog/testing-decorators-with-super-method/", priority: :low, tags:["testing"] },
{link: "https://isbgpsafeyet.com/", priority: :high,tags:["security", "networking"]},
{link: "https://arxiv.org/pdf/2002.05400v1.pdf", priority: :medium, tags:["security"] },
{link: "https://findka.com/blog/rec-sys-in-30-lines/", priority: :low, tags:["machine-learning", "clojure"] },
{link: "https://tryolabs.com/blog/2020/04/02/swift-googles-bet-on-differentiable-programming/", priority: :high, tags:["machine-learning"] },
{link: "https://blog.testdouble.com/posts/2020-04-07-favorite-things/", priority: :low, tags:["command-line"] },
{link: "https://www.driftingruby.com/episodes/google-maps-api-with-stimulusjs", priority: :low, tags:["misc"] },
{link: "https://emmanuelhayford.com/the-difference-between-self-method-name-and-class-self-in-ruby/", priority: :low, tags:["ruby"] },
{link: "https://blog.rebased.pl/2020/04/07/why-you-probably-dont-need-postgis.html", priority: :medium, tags:["misc"] },
{link: "https://www.youtube.com/watch?v=1HP-dckehqg", priority: :medium, tags:["reliability"] },
{link: "https://www.circonus.com/2018/07/a-guide-to-service-level-objectives/", priority: :medium, tags:["reliability"] },
{link: "https://ljvmiranda921.github.io/notebook/2019/11/08/flask-redis-celery-mcdo/", priority: :high, tags:["misc"] },
{link: "https://slack.engineering/deploys-at-slack-cd0d28c61701", priority: :high, tags:["devops", "reliability"] },
{link: "https://blcsystems.com/red-hat-free-courses/", priority: :low, tags:["misc"] },
{link: "https://www.microsoft.com/security/blog/2020/04/02/attack-matrix-kubernetes/", priority: :high, tags:["security", "k8s"] },
{link: "https://wiki.debian.org/WhyTheName", priority: :low, tags:["misc"] },
{link: "https://github.com/jesseduffield/lazygit#installation", priority: :medium, tags:["git", "command-line"] },
{link: "https://daniel-upton.com/articles/introduction-to-cassandra-for-sql-folk/", priority: :medium, tags:["databases"] },
{link: "https://developers.google.com/tech-writing/overview", priority: :medium, tags:["programming-tips", "career"] },
{link: "https://rachelbythebay.com/w/2020/02/07/kdir/", priority: :low, tags:["misc"] },
{link: "https://k8slens.dev/", priority: :low, tags:["k8s"]},
{link: "https://github.com/phuoc-ng/html-dom", priority: :high, tags:["front-end"] },
{link: "https://discuss.rubyonrails.org/t/why-is-rails-boot-so-slow-on-macos/74021", priority: :medium, tags:["rails", "containers"] },
{link: "https://fabioperrella.github.io/2020/03/30/an-index-route-without-pagination-can-destroy-your-app.html", priority: :low, tags:["debugging", "rails"] },
{link: "https://www.ombulabs.com/blog/ruby/learning/method-s-arguments-pt-1.html", priority: :low, tags:["rails"] },
{link: "https://github.com/simplabs/ast-workshop", priority: :high, tags:["misc"] },
{link: "https://engineering.shopify.com/blogs/engineering/refactoring-legacy-code-strangler-fig-pattern", priority: :high, tags:["rails", "reliability"] },
{link: "https://blog.appsignal.com/2020/03/18/facade-pattern-in-rails-for-performance-and-maintainability.html", priority: :low, tags:["rails"] },
{link: "https://schneems.com/2020/03/17/lies-damned-lies-and-averages-perc50-perc95-explained-for-programmers/", priority: :high, tags:["programming-tips"] },
{link: "https://boringrails.com/articles/spring-cleaning/", priority: :high, tags:["reliability"] },
{link: "https://robertheaton.com/2020/03/18/yourself-happier-iphone-worse/", priority: :medium, tags:["misc"] },
{link: "http://calpaterson.com/activerecord.html", priority: :high, tags:["databases"] },
{link: "https://discord.statuspage.io/incidents/62gt9cgjwdgf", priority: :high, tags:["reliability"] },
{link: "https://www.fastly.com/blog/network-automation-helps-support-worlds-biggest-live-streaming-moments", priority: :high, tags:["reliability", "networking"] },
{link: "https://kind.sigs.k8s.io/", priority: :medium, tags:["k8s"] },
{link: "https://codepen.io/ivorjetski/pen/xxGYWQG", priority: :high, tags:["front-end", "css"] },
{link: "https://github.com/gregnavis/active_record_doctor", priority: :high, tags:["databases", "rails"] },
{link: "https://prathamesh.tech/2020/03/18/diggin-through-hashes-and-arrays-in-ruby/", priority: :low, tags:["ruby"] },
{link: "https://blog.acolyer.org/2020/03/13/correlation-x-2/", priority: :high, tags:["reliability"] },
{link: "https://github.com/jamiebuilds/the-super-tiny-compiler", priority: :medium, tags:["misc"] },
{link: "https://blog.testdouble.com/posts/2020-02-25-necessary-and-sufficient/", priority: :medium, tags:["testing"] },
{link: "https://frontdeveloper.pl/2020/03/how-we-migrated-from-timecop-to-built-in-rails-5-2-time-helpers/", priority: :low, tags:["rails"] },
{link: "http://lists.busybox.net/pipermail/busybox/2010-December/074114.html", priority: :low, tags:["misc"] },
{link: "https://blog.acolyer.org/2016/10/06/simple-testing-can-prevent-most-critical-failures/", priority: :high, tags:["reliability"] },
{link: "https://opensource.com/article/18/5/cryptography-pki", priority: :medium, tags:["security"] },
{link: "https://opensource.com/article/19/11/internet-security-tls-ssl-certificate-authority", priority: :medium, tags:["security"] },
{link: "https://www.learningfromincidents.io/blog/learning-from-incidents-in-software", priority: :low, tags:["reliability"] },
{link: "https://www.learningfromincidents.io/blog/oops-learning-from-the-incident-you-didnt-have", priority: :medium, tags:["reliability"] },
{link: "https://www.honeycomb.io/framework-for-an-observability-maturity-model-using-observability-to-advance-your-engineering-product", priority: :high, tags:["reliability"]},
{link: "https://mads-hartmann.com/sre/2019/08/04/journey-into-observability-reading-material.html", priority: :high, tags:["reliability"] },
{link: "https://learnk8s.io/troubleshooting-deployments", priority: :high, tags:["k8s"] },
{link: "https://www.evanjones.ca/ordered-vs-unordered-indexes.html", priority: :high, tags:["databases", "data-structures"] },
{link: "https://github.com/docker-slim/docker-slim", priority: :low, tags:["containers"] },
{link: "https://reproducible-builds.org/tools/", priority: :low, tags:["misc"] },
{link: "https://smallstep.com/blog/everything-pki/", priority: :medium, tags:["security", "networking"] },
{link: "https://pythonspeed.com/articles/system-packages-docker/", priority: :low, tags:["containers"] },
{link: "https://blog.acolyer.org/2019/12/13/how-do-committees-invent/", priority: :high, tags:["misc", "management"] },
{link: "https://tls.ulfheim.net/", priority: :high, tags: ["networking"]},
{link: "https://gravitational.com/blog/ssh-handshake-explained/", priority: :high, tags:["security", "networking"] },
{link: "https://github.com/trekhleb/nano-neuron", priority: :high, tags:["machine-learning"] },
{link: "https://www.matestack.org/docs/install", priority: :low, tags:["front-end"] },
{link: "https://www.theregister.co.uk/2019/12/10/linux_kernel_aws/", priority: :high, tags:["security"] },
{link: "https://robertheaton.com/2019/12/21/ppab5-how-to-make-your-programs-shorter/", priority: :low, tags:["programming-tips"] },
{link: "https://www.redhat.com/en/topics/microservices/what-is-jaeger", priority: :low, tags:["reliability", "devops"] },
{link: "https://resilienceroundup.com/issues/61/", priority: :medium, tags:["reliability"] },
{link: "https://mystery.knightlab.com/", priority: :high, tags: ["sql"]},
{link: "https://danluu.com/deconstruct-files/", priority: :high, tags:["filesystems"] },
{link: "https://undraw.co/", priority: :low, tags:["front-end"]},
{link: "https://github.com/rotisserie/eris", priority: :low, tags:["go"] },
{link: "https://github.com/imsnif/bandwhich", priority: :low, tags:["command-line"] },
{link: "https://medium.com/better-programming/career-growth-frameworks-in-software-engineering-a-review-4aa6c59a9cf6", priority: :high, tags:["management", "career"] },
{link: "https://www.grahamlea.com/2013/07/why-smart-software-teams-dont-need-senior-developers-tech-leads-or-architects/", priority: :high, tags:["management", "career"] },
{link: "https://www.slideshare.net/reed2001/culture-1798664", priority: :low, tags:["management"] },
{link: "https://labs.spotify.com/2016/02/08/technical-career-path/", priority: :medium, tags:["career"] },
{link: "https://numeracy.co/blog/life-of-a-sql-query", priority: :high, tags:["sql", "databases"] },
{link: "https://www.taniarascia.com/", priority: :low,tags:["misc"]},
{link: "https://enmascript.com/articles/2019/04/22/avoid-recomputing-heavy-tasks-by-leveraging-memoization-in-javascript", priority: :high, tags:["js", "programming-tips"] },
{link: "https://netflixtechblog.com/python-at-netflix-bba45dae649e", priority: :low, tags:["misc"] },
{link: "https://www.vice.com/en_us/article/43zak3/the-internet-was-built-on-the-free-labor-of-open-source-developers-is-that-sustainable", priority: :low,tags:["tech-industry"]},
{link: "https://github.com/bridgecrewio/checkov", priority: :high, tags:["devops"] },
{link: "https://charemza.name/blog/posts/abstractions/http/http-guide-for-developers/", priority: :high, tags: ["networking"] },
{link: "https://bossanova.uk/jsuites/", priority: :low, tags: ["front-end", "js"]},
{link: "https://medium.com/@karen_meep/my-quick-turnaround-habit-db08c3ddb4b8", priority: :high, tags:["programming-tips", "career"] },
{link: "https://blog.acolyer.org/2020/01/08/ironies-of-automation/", priority: :high, tags:["programming-tips"] },
{link: "https://blog.acolyer.org/2020/01/10/ten-challenges-for-automation/", priority: :high, tags:["tech-industry", "programming-tips"] },
{link: "https://blog.acolyer.org/2020/01/13/challenges-of-real-world-rl/", priority: :high, tags: ["machine-learning"] },
{link: "https://pingcap.com/blog/chaos-mesh-your-chaos-engineering-solution-for-system-resiliency-on-kubernetes/", priority: :high, tags:["reliability", "k8s"] },
{link: "https://mads-hartmann.com/sre/2020/01/11/journey-into-observability-telemetry.html", priority: :high, tags:["reliability"] },
{link: "https://github.com/ahmetb/kubectl-tree", priority: :medium, tags:["k8s"] },
{link: "https://medium.com/@augmentable/looking-at-kubernetes-2k-todo-comments-b2db42dc7fdb", priority: :high, tags:["k8s", "command-line", "git"] },
{link: "https://snyk.io/blog/understanding-filesystem-takeover-vulnerabilities-in-npm-javascript-package-manager/", priority: :high, tags:["js", "security"] },
{link: "https://tersesystems.com/blog/2020/01/22/developing-in-production/", priority: :low, tags:["programming-tips"] },
{link: "https://cacheoutattack.com/CacheOut.pdf", priority: :medium, tags:["security"] },
{link: "https://pythonspeed.com/articles/alpine-docker-python/", priority: :low, tags:["containers"] },
{link: "https://0x65.dev/blog/2019-12-14/the-architecture-of-a-large-scale-web-search-engine-circa-2019.html", priority: :high, tags:["misc", "devops", "k8s"] },
{link: "https://github.com/binhnguyennus/awesome-scalability", priority: :high, tags:["comprehensive", "reliability"] },
{link: "https://blog.acolyer.org/2020/01/24/trade-offs-under-pressure-part-2/", priority: :high, tags:["debugging", "reliability"] },
{link: "https://blog.acolyer.org/2020/01/29/narrowing-the-gap/", priority: :low, tags:["cloud-computing", "databases"] },
{link: "https://superuser.blog/site-wide-memory-leak-on-call-story/", priority: :low, tags:["devops", "debugging"] },
{link: "https://robertheaton.com/2020/02/05/wacom-drawing-tablets-track-name-of-every-application-you-open/", priority: :low, tags:["security"] },
{link: "https://danluu.com/wat/", priority: :medium, tags: ["career", "misc"]},
{link: "https://www.paperplanes.de/2020/1/31/on-drafting-an-engineering-strategy.html", priority: :medium, tags:["management"] },
{link: "https://mtlynch.io/status-updates-to-nobody/", priority: :low, tags: ["programming-tips"] },
{link: "https://github.com/cli/cli", priority: :medium, tags:["command-line", "git"] },
{link: "https://robertheaton.com/2020/02/08/pfab9-batch-vs-stream-processing/", priority: :low, tags:["misc"] },
{link: "https://alexpareto.com/scalability/systems/2020/02/03/scaling-100k.html", priority: :high, tags: ["programming-tips", "reliability"] },
{link: "https://blog.acolyer.org/2020/02/10/watching-you-watch/", priority: :low, tags:["security"] },
{link: "https://www.datadoghq.com/blog/monitor-kubernetes-audit-logs/", priority: :low, tags:["k8s"] },
{link: "https://www.petefreitag.com/item/884.cfm", priority: :low, tags:["misc", "search"] },
{link: "https://www.ardanlabs.com/blog/2020/02/docker-images-part1-reducing-image-size.html", priority: :high, tags:["containers"] },
{link: "https://utcc.utoronto.ca/~cks/space/blog/sysadmin/RunningServersNotTrivial", priority: :high, tags:["devops", "reliability"] },
{link: "https://labs.ripe.net/Members/bert_hubert/centralised-doh-is-bad-for-privacy-in-2019-and-beyond", priority: :low, tags:["security", "misc"] },
{link: "https://opensource.com/article/20/2/yacy-search-engine-hacks", priority: :high, tags:["search", "misc"] },
{link: "https://cloud.google.com/blog/products/management-tools/sre-for-single-tiered-software-applications", priority: :medium, tags:["reliability"] },
{link: "https://robertheaton.com/2020/02/18/dont-let-magic-enhancer-for-youtube-slurp-up-your-browsing-history/", priority: :medium, tags:["security"] },
{link: "https://enterprisersproject.com/article/2019/9/emotional-intelligence-how-handle-criticism", priority: :medium, tags:["misc"] },
{link: "https://jvns.ca/blog/2019/11/18/how-containers-work--overlayfs/", priority: :high, tags:["containers"] },
{link: "https://blog.acolyer.org/2019/12/04/declarative-assembly-of-web-applications-from-pre-defined-concepts/", priority: :low, tags:["misc", "tech-industry"] },
{link: "https://github.com/haccer/subjack", priority: :medium, tags:["security"] },
{link: "https://blog.acolyer.org/2020/02/26/meaningful-availability/", priority: :high, tags:["reliability"] },
{link: "https://storiesinmypocket.com/articles/refactoring-and-asking-forgiveness/", priority: :medium, tags:["python", "reliability"] },
{link: "https://blog.acolyer.org/2020/02/14/programs-life-cycles-laws/", priority: :medium, tags:["misc"] },
{link: "https://www.learningfromincidents.io/blog/characteristics-of-next-level-incident-reports-in-software", priority: :high, tags:["reliability"] },
{link: "https://blog.acolyer.org/2020/02/28/microsoft-gandalf/", priority: :medium, tags:["reliability"] },
{link: "https://fasterthanli.me/blog/2020/i-want-off-mr-golangs-wild-ride/", priority: :low, tags:["go", "misc"] },
{link: "https://blog.deleu.dev/aws-vpc-for-software-engineers/", priority: :high, tags:["networking"] },
{link: "https://preslav.me/2020/03/01/use-the-git-history/", priority: :high, tags:["git", "command-line"] },
{link: "https://www.daolf.com/posts/best-programming-books/", priority: :medium, tags:["misc", "comprehensive"] },
{link: "http://pattle.github.io/simpsons-in-css/", priority: :low, tags:["misc"] },
{link: "https://www.brightbox.com/blog/2020/02/12/rubynetes-kubernetes-config-the-easy-way/", priority: :medium, tags:["k8s"] },
{link: "https://simongray.github.io/essays/spread.html", priority: :low, tags:["misc"] },
{link: "https://blog.alicegoldfuss.com/work-in-the-time-of-corona/", priority: :medium, tags:["misc", "career"] },
{link: "https://searchapparchitecture.techtarget.com/tip/3-microservices-resiliency-patterns-for-better-reliability", priority: :low, tags:["reliability"] },
{link: "https://engineering.shopify.com/blogs/engineering/circuit-breaker-misconfigured", priority: :high, tags:["reliability"] },
{link: "https://blog.appsignal.com/2020/03/04/building-a-rails-app-with-multiple-subdomains.html", priority: :low, tags:["networking"] },
{link: "https://changelog.com/posts/learning-by-example", priority: :low, tags:["programming-tips"] },
{link: "https://blog.cloudflare.com/the-history-of-the-url/", priority: :high, tags:["tech-industry", "networking"] },
{link: "https://blog.acolyer.org/2020/03/04/millions-of-tiny-databases/", priority: :medium, tags:["databases", "cloud-computing", "reliability"] },
{link: "https://monitoror.com/", priority: :medium, tags: ["reliability"]},
{link: "https://securek8s.dev/exercise/", priority: :medium, tags:["k8s", "security"] },
{link: "https://www.haproxy.com/user-spotlight-series/inside-the-github-load-balancer/", priority: :medium, tags: ["devops", "networking"] },
{link: "https://jvns.ca/blog/2019/11/20/what-makes-a-programming-exercise-good/", priority: :medium, tags: ["programming-tips"] },
{link: "https://nordicapis.com/understanding-the-hidden-powers-of-curl/", priority: :high, tags: ["networking"] },
{link: "https://docs.metaflow.org/", priority: :low, tags:["machine-learning"] },
{link: "https://opensource.com/article/19/10/know-about-sudo", priority: :low, tags: ["command-line"] },
{link: "https://www.redhat.com/cms/managed-files/ca-ito-security-checklist-f19123cs-201910-en_0.pdf", priority: :medium, tags: ["security"] },
{link: "https://www.redhat.com/sysadmin/bash-bang-commands", priority: :low, tags: ["command-line"] },
{link: "https://enterprisersproject.com/article/2019/11/kubernetes-3-ways-get-started", priority: :low, tags: ["k8s"] },
{link: "https://opensource.com/article/19/10/test-automation-without-assertions", priority: :low, tags: ["testing"] },
{link: "https://opensource.com/article/19/10/kubernetes-complex-business-problem", priority: :low, tags: ["devops"] },
{link: "https://robertheaton.com/2019/11/08/programming-feedback-for-advanced-beginners-0/", priority: :low, tags: ["programming-tips"] },
{link: "https://towardsdatascience.com/the-most-underrated-python-packages-e22bf6049b5e", priority: :low, tags: ["python"] },
{link: "https://pythonspeed.com/articles/docker-connection-refused/", priority: :high, tags: ["containers", "networking"] },
{link: "https://stackoverflow.blog/2019/09/30/how-to-make-good-code-reviews-better/", priority: :medium, tags: ["programming-tips"] },
{link: "https://blog.acolyer.org/2019/11/15/facebook-taiji/", priority: :high, tags: ["networking"] },
{link: "https://sweetalert2.github.io/", priority: :low, tags: ["front-end", "js"] },
{link: "https://peteris.rocks/blog/htop/", priority: :low, tags: ["command-line", "comprehensive"] },
{link: "https://learnk8s.io/production-best-practices", priority: :high, tags: ["devops", "k8s", "comprehensive"] },
{link: "https://almanac.httparchive.org/en/2019/", priority: :high, tags: ["networking", "tech-industry"] },
{link: "https://report-uri.com/#prices", priority: :low, tags: ["misc"] },
{link: "https://blog.acolyer.org/2019/11/18/formal-foundations-of-serverless-computing/", priority: :medium, tags: ["cloud-computing"] },
{link: "https://blog.acolyer.org/2019/11/20/local-first-software/", priority: :high, tags: ["tech-industry"] },
{link: "https://blog.acolyer.org/2019/11/22/planalyzer/", priority: :medium, tags: ["misc"] },
{link: "https://robertheaton.com/2019/11/11/pfab1/", priority: :low, tags: ["programming-tips"] },
{link: "https://robertheaton.com/2019/11/21/how-to-man-in-the-middle-your-iot-devices/", priority: :medium, tags: ["security", "networking"] },
{link: "https://github.com/omarroth/invidious", priority: :low, tags: ["misc"] },
{link: "https://github.com/cloudflare/flan", priority: :low, tags: ["security"] },
{link: "https://github.com/Kayzaks/HackingNeuralNetworks", priority: :low, tags: ["machine-learning"] },
{link: "https://opensource.com/article/19/11/introduction-monitoring-prometheus", priority: :low, tags: ["reliability"] },
{link: "https://www.redhat.com/sysadmin/basic-security-principles-containers", priority: :low, tags: ["security","containers"] },
{link: "https://blog.acolyer.org/2015/05/01/staring-into-the-abyss-an-evaluation-of-concurrency-control-with-one-thousand-cores/", priority: :low, tags: ["databases"] },
{link: "https://www.redhat.com/sysadmin/manipulating-text-grep", priority: :low, tags: ["command-line"] },
{link: "https://www.gwern.net/Complement", priority: :low, tags: ["tech-industry"] },
{link: "https://blog.pragmaticengineer.com/a-team-where-everyone-is-a-leader/", priority: :medium, tags: ["management"] },
{link: "https://hakibenita.com/sql-dos-and-donts", priority: :medium, tags: ["sql", "databases"]},
{link: "https://github.com/chiphuyen/machine-learning-systems-design", priority: :medium, tags: ["machine-learning"] },
{link: "https://www.youtube.com/watch?reload=9&v=rYzmXLhIaHQ", priority: :medium, tags: ["devops", "reliability"]},
{link: "https://hackernoon.com/deploy-on-fridays-or-dont-qg2y32jk", priority: :low, tags: ["devops"]},
{link: "https://thenewstack.io/new-cryptojacking-worm-found-in-docker-containers/", priority: :low, tags: ["security"]},
{link: "https://unit42.paloaltonetworks.com/graboid-first-ever-cryptojacking-worm-found-in-images-on-docker-hub/", priority: :low, tags: ["security"] },
{link: "https://css-tricks.com/why-parcel-has-become-my-go-to-bundler-for-development/", priority: :low, tags: ["front-end"] },
{link: "https://engineering.shopify.com/blogs/engineering/five-common-data-stores-usage", priority: :medium, tags: ["databases"] },
{link: "https://sneak.berlin/20191011/stupid-unix-tricks/", priority: :low, tags: ["misc","unix"]},
{link: "https://opensource.com/article/19/10/open-source-observability-kubernetes", priority: :medium, tags: ["reliability","k8s"]},
{link: "https://blog.acolyer.org/2019/10/28/interpretable-models/", priority: :low, tags: ["misc"]},
{link: "https://blog.acolyer.org/2019/10/30/corels/", priority: :low, tags: ["misc"] },
{link: "https://blog.acolyer.org/2019/11/01/optimized-risk-scores/", priority: :low, tags: ["misc"] },
{link: "https://alexdanco.com/2019/10/26/everything-is-amazing-but-nothing-is-ours/", priority: :low, tags: ["tech-industry"] },
{link: "https://github.com/Tikam02/DevOps-Guide", priority: :medium, tags: ["comprehensive","devops"] },
{link: "https://www.wezm.net/technical/2019/10/useful-command-line-tools/#alt", priority: :low, tags: ["command-line"] },
{link: "https://blog.acolyer.org/2019/11/08/the-inflection-point-hypothesis/", priority: :low, tags: ["debugging"] },
{link: "https://blog.acolyer.org/2019/11/04/an-analysis-of-performance-evolution-of-linuxs-core-operations/", priority: :medium, tags: ["kernel","linux"] },
{link: "https://blog.acolyer.org/2019/11/06/ceph-evolution/", priority: :low, tags: ["filesystems"]},
{link: "http://divio.com/blog/documentation/", priority: :medium, tags: ["documentation"] },
{link: "https://engineering.instawork.com/when-xml-beats-json-ui-layouts-53c7f1d3fdb7", priority: :low, tags: ["data-structures","js"] },
{link: "https://blog.acolyer.org/2019/07/12/view-centric-performance-optimization/", priority: :low, tags: ["performance"] },
{link: "https://www.nemil.com/musings/hack-an-engineer.html", priority: :low, tags: ["tech-industry"] },
{link: "https://nullsweep.com/http-security-headers-a-complete-guide/", priority: :medium, tags: ["networking","security"] },
{link: "https://blog.regehr.org/archives/199", priority: :low, tags: ["programming-tips","debugging"] },
{link: "https://manybutfinite.com/post/how-computers-boot-up/", priority: :low, tags: ["kernel","CPU","misc"] },
{link: "https://blog.acolyer.org/2019/09/23/the-secret-sharer/", priority: :medium, tags: ["machine-learning"] },
{link: "https://blog.acolyer.org/2019/09/25/50-ways-to-leak-your-data/", priority: :low, tags: ["android","security"] },
{link: "https://blog.acolyer.org/2019/09/30/small-world-with-high-risks/", priority: :low, tags: ["js","npm","security"] },
{link: "https://learnk8s.io/kubernetes-node-size", priority: :low, tags: ["k8s"] },
{link: "https://jvns.ca/blog/brag-documents/", priority: "medium", tags: ["career"]}]
